/*----- PROTECTED REGION ID(TwoChannelAdapter.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        TwoChannelAdapter.cpp
//
// description : C++ source for the TwoChannelAdapter class and its commands.
//               The class is derived from Device. It represents the
//               CORBA servant object which will be accessed from the
//               network. All commands which can be executed on the
//               TwoChannelAdapter are implemented in this file.
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <TwoChannelAdapter.h>
#include <TwoChannelAdapterClass.h>

/*----- PROTECTED REGION END -----*/	//	TwoChannelAdapter.cpp

/**
 *  TwoChannelAdapter class description:
 *    
 */

//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name  |  Method name
//================================================================
//  State         |  Inherited (no method)
//  Status        |  Inherited (no method)
//  StopMove      |  stop_move
//  RestMotor     |  rest_motor
//================================================================

//================================================================
//  Attributes managed is:
//================================================================
//  Position  |  Tango::DevDouble	Scalar
//================================================================

namespace TwoChannelAdapter_ns
{
/*----- PROTECTED REGION ID(TwoChannelAdapter::namespace_starting) ENABLED START -----*/

//	static initializations

/*----- PROTECTED REGION END -----*/	//	TwoChannelAdapter::namespace_starting

//--------------------------------------------------------
/**
 *	Method      : TwoChannelAdapter::TwoChannelAdapter()
 *	Description : Constructors for a Tango device
 *                implementing the classTwoChannelAdapter
 */
//--------------------------------------------------------
TwoChannelAdapter::TwoChannelAdapter(Tango::DeviceClass *cl, string &s)
 : TANGO_BASE_CLASS(cl, s.c_str())
{
	/*----- PROTECTED REGION ID(TwoChannelAdapter::constructor_1) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	TwoChannelAdapter::constructor_1
}
//--------------------------------------------------------
TwoChannelAdapter::TwoChannelAdapter(Tango::DeviceClass *cl, const char *s)
 : TANGO_BASE_CLASS(cl, s)
{
	/*----- PROTECTED REGION ID(TwoChannelAdapter::constructor_2) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	TwoChannelAdapter::constructor_2
}
//--------------------------------------------------------
TwoChannelAdapter::TwoChannelAdapter(Tango::DeviceClass *cl, const char *s, const char *d)
 : TANGO_BASE_CLASS(cl, s, d)
{
	/*----- PROTECTED REGION ID(TwoChannelAdapter::constructor_3) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	TwoChannelAdapter::constructor_3
}

//--------------------------------------------------------
/**
 *	Method      : TwoChannelAdapter::delete_device()
 *	Description : will be called at device destruction or at init command
 */
//--------------------------------------------------------
void TwoChannelAdapter::delete_device()
{
	DEBUG_STREAM << "TwoChannelAdapter::delete_device() " << device_name << endl;
	/*----- PROTECTED REGION ID(TwoChannelAdapter::delete_device) ENABLED START -----*/
	
	//	Delete device allocated objects
	
	/*----- PROTECTED REGION END -----*/	//	TwoChannelAdapter::delete_device
	delete[] attr_Position_read;
}

//--------------------------------------------------------
/**
 *	Method      : TwoChannelAdapter::init_device()
 *	Description : will be called at device initialization.
 */
//--------------------------------------------------------
void TwoChannelAdapter::init_device()
{
	DEBUG_STREAM << "TwoChannelAdapter::init_device() create device " << device_name << endl;
	/*----- PROTECTED REGION ID(TwoChannelAdapter::init_device_before) ENABLED START -----*/
	
	//	Initialization before get_device_property() call
	
	/*----- PROTECTED REGION END -----*/	//	TwoChannelAdapter::init_device_before
	

	//	Get the device properties from database
	get_device_property();
	
	attr_Position_read = new Tango::DevDouble[1];
	/*----- PROTECTED REGION ID(TwoChannelAdapter::init_device) ENABLED START -----*/
	
	//	Initialize device
	
	/*----- PROTECTED REGION END -----*/	//	TwoChannelAdapter::init_device
}

//--------------------------------------------------------
/**
 *	Method      : TwoChannelAdapter::get_device_property()
 *	Description : Read database to initialize property data members.
 */
//--------------------------------------------------------
void TwoChannelAdapter::get_device_property()
{
	/*----- PROTECTED REGION ID(TwoChannelAdapter::get_device_property_before) ENABLED START -----*/
	
	//	Initialize property data members
	
	/*----- PROTECTED REGION END -----*/	//	TwoChannelAdapter::get_device_property_before


	//	Read device properties from database.
	Tango::DbData	dev_prop;
	dev_prop.push_back(Tango::DbDatum("channel"));

	//	is there at least one property to be read ?
	if (dev_prop.size()>0)
	{
		//	Call database and extract values
		if (Tango::Util::instance()->_UseDb==true)
			get_db_device()->get_property(dev_prop);
	
		//	get instance on TwoChannelAdapterClass to get class property
		Tango::DbDatum	def_prop, cl_prop;
		TwoChannelAdapterClass	*ds_class =
			(static_cast<TwoChannelAdapterClass *>(get_device_class()));
		int	i = -1;

		//	Try to initialize channel from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  channel;
		else {
			//	Try to initialize channel from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  channel;
		}
		//	And try to extract channel value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  channel;

	}

	/*----- PROTECTED REGION ID(TwoChannelAdapter::get_device_property_after) ENABLED START -----*/
	
	//	Check device property data members init
	
	/*----- PROTECTED REGION END -----*/	//	TwoChannelAdapter::get_device_property_after
}

//--------------------------------------------------------
/**
 *	Method      : TwoChannelAdapter::always_executed_hook()
 *	Description : method always executed before any command is executed
 */
//--------------------------------------------------------
void TwoChannelAdapter::always_executed_hook()
{
	DEBUG_STREAM << "TwoChannelAdapter::always_executed_hook()  " << device_name << endl;
	/*----- PROTECTED REGION ID(TwoChannelAdapter::always_executed_hook) ENABLED START -----*/
	
	//	code always executed before all requests
	
	/*----- PROTECTED REGION END -----*/	//	TwoChannelAdapter::always_executed_hook
}

//--------------------------------------------------------
/**
 *	Method      : TwoChannelAdapter::read_attr_hardware()
 *	Description : Hardware acquisition for attributes
 */
//--------------------------------------------------------
void TwoChannelAdapter::read_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "TwoChannelAdapter::read_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(TwoChannelAdapter::read_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	TwoChannelAdapter::read_attr_hardware
}
//--------------------------------------------------------
/**
 *	Method      : TwoChannelAdapter::write_attr_hardware()
 *	Description : Hardware writing for attributes
 */
//--------------------------------------------------------
void TwoChannelAdapter::write_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "TwoChannelAdapter::write_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(TwoChannelAdapter::write_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	TwoChannelAdapter::write_attr_hardware
}

//--------------------------------------------------------
/**
 *	Read attribute Position related method
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TwoChannelAdapter::read_Position(Tango::Attribute &attr)
{
	DEBUG_STREAM << "TwoChannelAdapter::read_Position(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(TwoChannelAdapter::read_Position) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_Position_read);
	
	/*----- PROTECTED REGION END -----*/	//	TwoChannelAdapter::read_Position
}
//--------------------------------------------------------
/**
 *	Write attribute Position related method
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void TwoChannelAdapter::write_Position(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TwoChannelAdapter::write_Position(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevDouble	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TwoChannelAdapter::write_Position) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TwoChannelAdapter::write_Position
}

//--------------------------------------------------------
/**
 *	Method      : TwoChannelAdapter::add_dynamic_attributes()
 *	Description : Create the dynamic attributes if any
 *                for specified device.
 */
//--------------------------------------------------------
void TwoChannelAdapter::add_dynamic_attributes()
{
	/*----- PROTECTED REGION ID(TwoChannelAdapter::add_dynamic_attributes) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic attributes if any
	
	/*----- PROTECTED REGION END -----*/	//	TwoChannelAdapter::add_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Command StopMove related method
 *	Description: 
 *
 */
//--------------------------------------------------------
void TwoChannelAdapter::stop_move()
{
	DEBUG_STREAM << "TwoChannelAdapter::StopMove()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(TwoChannelAdapter::stop_move) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	TwoChannelAdapter::stop_move
}
//--------------------------------------------------------
/**
 *	Command RestMotor related method
 *	Description: 
 *
 */
//--------------------------------------------------------
void TwoChannelAdapter::rest_motor()
{
	DEBUG_STREAM << "TwoChannelAdapter::RestMotor()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(TwoChannelAdapter::rest_motor) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	TwoChannelAdapter::rest_motor
}
//--------------------------------------------------------
/**
 *	Method      : TwoChannelAdapter::add_dynamic_commands()
 *	Description : Create the dynamic commands if any
 *                for specified device.
 */
//--------------------------------------------------------
void TwoChannelAdapter::add_dynamic_commands()
{
	/*----- PROTECTED REGION ID(TwoChannelAdapter::add_dynamic_commands) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic commands if any
	
	/*----- PROTECTED REGION END -----*/	//	TwoChannelAdapter::add_dynamic_commands
}

/*----- PROTECTED REGION ID(TwoChannelAdapter::namespace_ending) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	TwoChannelAdapter::namespace_ending
} //	namespace
