/*----- PROTECTED REGION ID(TwoChannelAdapter.h) ENABLED START -----*/
//=============================================================================
//
// file :        TwoChannelAdapter.h
//
// description : Include file for the TwoChannelAdapter class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef TwoChannelAdapter_H
#define TwoChannelAdapter_H

#include <tango.h>
#include <pcidevfunctions.h>


/*----- PROTECTED REGION END -----*/	//	TwoChannelAdapter.h

/**
 *  TwoChannelAdapter class description:
 *    
 */

namespace TwoChannelAdapter_ns
{
/*----- PROTECTED REGION ID(TwoChannelAdapter::Additional Class Declarations) ENABLED START -----*/

//	Additional Class Declarations

/*----- PROTECTED REGION END -----*/	//	TwoChannelAdapter::Additional Class Declarations

class TwoChannelAdapter : public TANGO_BASE_CLASS
{

/*----- PROTECTED REGION ID(TwoChannelAdapter::Data Members) ENABLED START -----*/

public:
	PciDevFunctions *pciDev;

/*----- PROTECTED REGION END -----*/	//	TwoChannelAdapter::Data Members

//	Device property data members
public:
	//	channel:	0 channel or 1 channel
	Tango::DevShort	channel;
	//	port_path:	
	string	port_path;
	//	frequency:	Frequency in Hz
	Tango::DevDouble	frequency;

//	Attribute data members
public:
	Tango::DevDouble	*attr_Position_read;

//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	TwoChannelAdapter(Tango::DeviceClass *cl,string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	TwoChannelAdapter(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	TwoChannelAdapter(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */
	~TwoChannelAdapter() {delete_device();};


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Read the device properties from database
	 */
	void get_device_property();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();


//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method      : TwoChannelAdapter::read_attr_hardware()
	 *	Description : Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(vector<long> &attr_list);
	//--------------------------------------------------------
	/*
	 *	Method      : TwoChannelAdapter::write_attr_hardware()
	 *	Description : Hardware writing for attributes.
	 */
	//--------------------------------------------------------
	virtual void write_attr_hardware(vector<long> &attr_list);

/**
 *	Attribute Position related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_Position(Tango::Attribute &attr);
	virtual void write_Position(Tango::WAttribute &attr);
	virtual bool is_Position_allowed(Tango::AttReqType type);


	//--------------------------------------------------------
	/**
	 *	Method      : TwoChannelAdapter::add_dynamic_attributes()
	 *	Description : Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();




//	Command related methods
public:
	/**
	 *	Command StopMove related method
	 *	Description: 
	 *
	 */
	virtual void stop_move();
	virtual bool is_StopMove_allowed(const CORBA::Any &any);
	/**
	 *	Command RestMotor related method
	 *	Description: 
	 *
	 */
	virtual void rest_motor();
	virtual bool is_RestMotor_allowed(const CORBA::Any &any);
	/**
	 *	Command Calibrate related method
	 *	Description: 
	 *
	 */
	virtual void calibrate();
	virtual bool is_Calibrate_allowed(const CORBA::Any &any);


	//--------------------------------------------------------
	/**
	 *	Method      : TwoChannelAdapter::add_dynamic_commands()
	 *	Description : Add dynamic commands if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_commands();

/*----- PROTECTED REGION ID(TwoChannelAdapter::Additional Method prototypes) ENABLED START -----*/

//	Additional Method prototypes

/*----- PROTECTED REGION END -----*/	//	TwoChannelAdapter::Additional Method prototypes
};

/*----- PROTECTED REGION ID(TwoChannelAdapter::Additional Classes Definitions) ENABLED START -----*/

//	Additional Classes Definitions

/*----- PROTECTED REGION END -----*/	//	TwoChannelAdapter::Additional Classes Definitions

}	//	End of namespace

#endif   //	TwoChannelAdapter_H
