/*----- PROTECTED REGION ID(TwoChannelAdapterStateMachine.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        TwoChannelAdapterStateMachine.cpp
//
// description : State machine file for the TwoChannelAdapter class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <TwoChannelAdapter.h>

/*----- PROTECTED REGION END -----*/	//	TwoChannelAdapter::TwoChannelAdapterStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace TwoChannelAdapter_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : TwoChannelAdapter::is_MotionRight_allowed()
 *	Description : Execution allowed for MotionRight attribute
 */
//--------------------------------------------------------
bool TwoChannelAdapter::is_MotionRight_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for MotionRight command.
	/*----- PROTECTED REGION ID(TwoChannelAdapter::MotionRightStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TwoChannelAdapter::MotionRightStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : TwoChannelAdapter::is_MotionLeft_allowed()
 *	Description : Execution allowed for MotionLeft attribute
 */
//--------------------------------------------------------
bool TwoChannelAdapter::is_MotionLeft_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for MotionLeft command.
	/*----- PROTECTED REGION ID(TwoChannelAdapter::MotionLeftStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TwoChannelAdapter::MotionLeftStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : TwoChannelAdapter::is_Stop_allowed()
 *	Description : Execution allowed for Stop attribute
 */
//--------------------------------------------------------
bool TwoChannelAdapter::is_Stop_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Stop command.
	/*----- PROTECTED REGION ID(TwoChannelAdapter::StopStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TwoChannelAdapter::StopStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(TwoChannelAdapter::TwoChannelAdapterStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	TwoChannelAdapter::TwoChannelAdapterStateAllowed.AdditionalMethods

}	//	End of namespace
